name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - name: Build
      run: go build -v ./test_setupApp.go
    - name: Test
      run: go test -v ./test_setupApp.go

